[ad]
user = "gogo"
pass = "xyz"
addr = "ad.upr.edu.cu:636"
bdn = "dc=upr,dc=edu,dc=cu"
suff = "@upr.edu.cu"

admins = ["luis.mendez"]

dialTimeout = "10s"


[sessionM]
	
	[sesionM-1]
	name = "sm"
	admins = ["luis.mendez"]

[logger]
ipUser = "sm"
addr = ""